name: publish

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Release build
      run: dotnet build -c Release
    - name: Pack
      run: dotnet pack -c Release -o ./pack/
    - name: Push to NuGet
      run: dotnet nuget push ./pack/Folleach.ConsoleUtils.*.nupkg -k ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json --skip-duplicate